name: twinkletaps-app CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    uses: ./.github/workflows/twinkletaps-app--install-dependencies.yml

  lint:
    needs: install-dependencies
    uses: ./.github/workflows/twinkletaps-app--lint.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  build:
    needs: install-dependencies
    uses: ./.github/workflows/twinkletaps-app--build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  test:
    needs: install-dependencies
    uses: ./.github/workflows/twinkletaps-app--test.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  e2e:
    needs: install-dependencies
    uses: ./.github/workflows/twinkletaps-app--e2e.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
