name: twinkletaps-app Unit and Component Tests
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:54322/postgres"
    defaults:
      run:
        working-directory: twinkletaps-app
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: twinkletaps-app/node_modules
          key: ${{ inputs.cache-key }}

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('twinkletaps-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright dependencies
        run: |
          npx playwright install --with-deps

      - name: Test
        run: npm run test
